### ISSUE TITLE
Agregar todas las soluciones en la imagen del carrusel

### ISSUE THREAD

**Issue by ODanielHernandez** [FragmentoEstudio/bitaez#7]
Aquí te los dejo:

-Estética facial
-Medicina general
-Ginecología
-Angiología y cirugía vascular
-Traumatología
-Cirugía general
-Otorrinolaringología
-Laboratorio químico
-Psiquiatría y psicología
-Hemodialisis
-Nefrólogía

**Comment by luisvega1** [comment]
Issue resuelto con merge del pull request #8
